// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ticker.proto

package gogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TickerStreamService_TickerStream_FullMethodName = "/gogen.TickerStreamService/TickerStream"
)

// TickerStreamServiceClient is the client API for TickerStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerStreamServiceClient interface {
	TickerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TickerRequest, TickerResponse], error)
}

type tickerStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerStreamServiceClient(cc grpc.ClientConnInterface) TickerStreamServiceClient {
	return &tickerStreamServiceClient{cc}
}

func (c *tickerStreamServiceClient) TickerStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TickerRequest, TickerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TickerStreamService_ServiceDesc.Streams[0], TickerStreamService_TickerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TickerRequest, TickerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TickerStreamService_TickerStreamClient = grpc.BidiStreamingClient[TickerRequest, TickerResponse]

// TickerStreamServiceServer is the server API for TickerStreamService service.
// All implementations must embed UnimplementedTickerStreamServiceServer
// for forward compatibility.
type TickerStreamServiceServer interface {
	TickerStream(grpc.BidiStreamingServer[TickerRequest, TickerResponse]) error
	mustEmbedUnimplementedTickerStreamServiceServer()
}

// UnimplementedTickerStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTickerStreamServiceServer struct{}

func (UnimplementedTickerStreamServiceServer) TickerStream(grpc.BidiStreamingServer[TickerRequest, TickerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TickerStream not implemented")
}
func (UnimplementedTickerStreamServiceServer) mustEmbedUnimplementedTickerStreamServiceServer() {}
func (UnimplementedTickerStreamServiceServer) testEmbeddedByValue()                             {}

// UnsafeTickerStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerStreamServiceServer will
// result in compilation errors.
type UnsafeTickerStreamServiceServer interface {
	mustEmbedUnimplementedTickerStreamServiceServer()
}

func RegisterTickerStreamServiceServer(s grpc.ServiceRegistrar, srv TickerStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedTickerStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TickerStreamService_ServiceDesc, srv)
}

func _TickerStreamService_TickerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TickerStreamServiceServer).TickerStream(&grpc.GenericServerStream[TickerRequest, TickerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TickerStreamService_TickerStreamServer = grpc.BidiStreamingServer[TickerRequest, TickerResponse]

// TickerStreamService_ServiceDesc is the grpc.ServiceDesc for TickerStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogen.TickerStreamService",
	HandlerType: (*TickerStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TickerStream",
			Handler:       _TickerStreamService_TickerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ticker.proto",
}
